### ISSUE TITLE
Edit environment requirements and instructions

### ISSUE THREAD

**Issue by evasterviga** [LucijaOstojic/Project_LO#1]
What a clearly written code and clear instructions. Vey good!

I would like you to edit a few things regarding the required packages. Please go through the points written below, fix them and see if it works in your own newly made environment. If you are unsure about anything, don't hesitate to contact me and we will solve it together.

### Creating an environment:
First, I would like some instructions on how to install the required packages in a separate environment. Instructions on how to create an environment are in the presentation 2023_Day2_VirtualEnvs.pptx in canvas. Or you can find it on google.

### Error messages to get rid of

1. After creating and activating a new environment and running `pip install -r requirements.txt` there might be an error message saying this: `bash: pip: command not found`

2. After installing pip there might be some issues with these lines in `requirements.txt`:
```
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
```
giving the following kind of error:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/croot/mkl_fft_1695058164594/work'
```

Are these packages required to run the script? It seems I can run it after deleting these lines from `requirements.txt` and installing the other packages. 

3. Moreover the specified numpy and scipy distributions are giving teh following kind of errors:
```
ERROR: Could not find a version that satisfies the requirement scipy==1.11.3 (from -r requirements.txt (line 8)) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3)

ERROR: No matching distribution found for scipy==1.11.3 (from -r requirements.txt (line 8))
```
An easy fix could be to remove the distribution requirements of these packages.

**Comment by LucijaOstojic** [comment]
Hi!

I tried to fix it by adding an environment .yml file, I hope it works now. At least it works in a fresh environment on my laptop, I had nowhere else to test it, unfortunately.

**Comment by evasterviga** [comment]
Very nice! It all works well and is very easy to follow, just how we like it.
